- hosts: webserver
  remote_user: root
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest

  - name: start httpd
    service:
      name: httpd
      state: started

  - name: restart httpd
    service:
      name: httpd
      state: restarted
